### PR TITLE
Rlhf

### PR DESCRIPTION
**Pull request by sanagno**
(mostly) Placeholder code for RLHF. @theblackcat102  Let me what you think about the structure. I think at this point we should choose one model and start to create scripts that go from start to finish.

### CODE REVIEW

**Comment by theblackcat102** [comment]
placing under supervised feels odd, I was thinking of placing it under reward/training(or learning ) or a new folder ( RL perhaps )?

**Comment by sanagno** [comment]
That is how I started but then realised that most of the things are/will be already shared, including models, utils and partially pre-processing. We can also think about have some common utils somewhere for all models, whatever you prefer.

**Comment by theblackcat102** [comment]
Hmm, how about renaming the supervised_tuning to like `rlhf` or model training? Since the first step for all related RLHF on language model start with SFT so I guess it makes sense to place our supervised training code inside?

**Comment by theblackcat102** [comment]
But I would suggest doing it in a two step process, create the new directory in the first PR and we move the supervised_tuning code in the second PR. Cause some contributors might be working on the old scheme

**Comment by sanagno** [comment]
Good idea actualy

**Pull request closed without merging**
