### PR TITLE
pre-commit hook black->black-jupyter

### PR DESCRIPTION
**Pull request by janosh**
[`black` supports formatting Jupyter notebooks](https://black.readthedocs.io/en/stable/integrations/source_version_control.html#version-control-integration).

This PR does not include the changes that would result from

```sh
pre-commit run black-jupyter --all-files
```

Happy to add them if this gets approval.

### CODE REVIEW

**Comment by yk** [comment]
LGTM, thank you, didn't know. Could you remove the notebooks from exclude?

**Review by yk — APPROVED** [review]
LGTM, thank you

**Review by bitplane — APPROVED** [review]

**Comment by janosh** [comment]
@yk I removed the notebooks exclusion from `.pre-commit-config.yaml`.

**Review by yk — APPROVED** [review]
thank you!

**Pull request merged**
