### PR TITLE
Add chat deletion functionality

### PR DESCRIPTION
**Pull request by AbdBarho**
Allow users to delete their own chats

Maybe some python wizard can clean up the monstrosity of query I wrote for deletion, I could not get the chat deletion to cascade, so I had to clear the messages first.

### CODE REVIEW

**Comment by notmd** [comment]
Can we make it soft delete instead?

**Comment by AbdBarho** [comment]
> Can we make it soft delete instead?

We can, I am not sure if GDPR would be happy about it, unless we have it in our terms of service.

**Comment by notmd** [comment]
Be careful when merging this, it will delete messages that we will use for RL. we better remove the foreign key or soft delete the message.

**Comment by olliestanley** [comment]
> Be careful when merging this, it will delete messages that we will use for RL. we better remove the foreign key or soft delete the message.

I see the logic to favour soft deletion but I would be concerned about people not being able to delete their data fully if they accidentally input private/compromising info

**Comment by notmd** [comment]
> I see the logic to favour soft deletion but I would be concerned about people not being able to delete their data fully if they accidentally input private/compromising info

Yeah, we should ask the user for this. But for me, most of the time I want to delete all the chats because I want to make it easier to manage chats (I believe many other users would do the same). If we always delete messages, we wont get any data to improve the model.

**Review by notmd — APPROVED** [review]
web changes LGTM, but we better discuss this before merging the PR

**Comment by AbdBarho** [comment]
I am going to merge this one with the functionality disabled, meaning the user still can't delete, but the code is there.

I think we should add the "hide" option first, then enable this one.

I unlinked the issues.

**Comment by olliestanley** [comment]
> I am going to merge this one with the functionality disabled, meaning the user still can't delete, but the code is there.
> 
> I think we should add the "hide" option first, then enable this one.
> 
> I unlinked the issues.

I think we should also make sure the "hide" option is clearer and easier to click in the UI when we do this

**Pull request merged**
