### PR TITLE
Adding new Dutch (NL) translations

### PR DESCRIPTION
**Pull request by tijsmaas**
Could you assign the label i18n, thanks!

### CODE REVIEW

**Comment by notmd** [comment]
You need to add the language code to next-i18next.config.js too

**Review by fozziethebeat — CHANGES_REQUESTED** [review]
As @notmd noted, you have to update `website/next-i18next.config.js` and add `nl` to the list.

**Review by fozziethebeat — CHANGES_REQUESTED** [review]
I see a lot of merge conflcits.  Did these changes get submitted in a different PR? Can you check if this is still needed?

**Comment by notmd** [comment]
I think this can be closed now. #1514 has cover this already

**Pull request closed without merging**
