### PR TITLE
add some "paths" to `test-api-contract.yaml`

### PR DESCRIPTION
**Pull request by andrewm4894**
It seems to maybe be running a lot of the time. 

A starter PR for this issue: https://github.com/LAION-AI/Open-Assistant/issues/627

### CODE REVIEW

**Comment by yk** [comment]
I'd rather include than exclude.
also, the same paths need to go into the pull request even

**Comment by andrewm4894** [comment]
> I'd rather include than exclude. also, the same paths need to go into the pull request even

yeah - was just a bit unsure what paths we should use for include - any idea? i can rejig as needed if someone can give me a quick list.

**Comment by andrewm4894** [comment]
Actually looking at the workflow itself it looks like maybe its just 

- oasst-shared/**
- backend/**
- website/**

but was just hesitant in case can be some other dependencies im not aware of

**Review by yk — COMMENTED** [review]
yes, this looks good, thank you :)

**Review by yk — APPROVED** [review]

**Pull request merged**
