### PR TITLE
Added code instructions notebook

### PR DESCRIPTION
**Pull request by GravermanDev**
Added a notebook to convert code into instructions on how to build that code. This model will be refined later but it is working failry well right now. This solves issue #297

### CODE REVIEW

**Comment by andrewm4894** [comment]
you should have just continued working in this PR instead, no? 

https://github.com/LAION-AI/Open-Assistant/pull/624

**Comment by GravermanDev** [comment]
I accidentally close this PR, doesn't matter really @andrewm4894

**Comment by andrewm4894** [comment]
just adding my same comment from the other PR https://github.com/LAION-AI/Open-Assistant/pull/624#issuecomment-1378702463

**Comment by yk** [comment]
@GravermanDev did you already address comments from #624 ?

> @GravermanDev cool - cant wait to play with this :)
>
> can you add it into the notebooks/ folder and try follow similar example like this one:
> https://github.com/GravermanDev/Open-Assistant/tree/main/notebooks/example
>
> pip install looks good at top of notebook maybe just try and:
>
> - add open in colab button cell to the top.
> - submit the notebook as ran with output so people browsing the repo can easily just see outputs from each cell.
> - maybe change CodeInstructions.md to README.md so will render the readme automatically in github.

**Review by 53jk1 — APPROVED** [review]

**Comment by yk** [comment]
@53jk1 please stop blanket-approving all PRs. if you have specific constructive comments for improvements, leave those, otherwise code owners are the ones reviewing

**Comment by andrewm4894** [comment]
I think this might need to be updated from upstream/master to be able to merge since a few things have since changed a little in the /notebooks folder.

**Pull request closed without merging**
