### PR TITLE
update docusaurus to latest + add models yt video as blogpost

### PR DESCRIPTION
**Pull request by andrewm4894**
- update docusaurus to latest
- add models yt video as a blog post

Note: The docusaurus update is needed as i was hitting some dependency hell trying to add the blog post so was worth doing the update as part of this too.

### CODE REVIEW

**Comment by olliestanley** [comment]
Looks like the deploy is failing. Is that due to the docusaurus upgrade?

**Comment by andrewm4894** [comment]
i think so - looks like the gh action here a little different: https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions

trying the latest version of the gh action

**Comment by andrewm4894** [comment]
making draft until sort the gh action

**Comment by andrewm4894** [comment]
working again (somehow :) )

**Review by olliestanley — APPROVED** [review]

**Comment by andrewm4894** [comment]
@andreaskoepf or @yk this will probably need one of your approvals since needed to update the docs GH action to have the new blog post work properly since lastest update to docusaruas.

**Review by yk — APPROVED** [review]
thank you very much!

**Pull request merged**
