### PR TITLE
Add lang-tag based task selection (lang-separation)

### PR DESCRIPTION
**Pull request by andreaskoepf**
- `ConversationMessage`, `TextReplyToMessage` and `TaskRequest` now have `lang` property, if no value is provided 'en' is assumed
- POST `api/v1/tasks/availability` endpoint has a `lang` param
- default for lang column of message table  is now 'en' (was 'en-US')
- task selection in TreeManager is language-dependent

### CODE REVIEW

**Review by yk — APPROVED** [review]
really cool, thank you.
It may be worth to think about always considering a set of languages, instead of only one, i.e. a user could ask for a task in either of their languages, and a task could be appropriate for either of two languages (i.e. translate from one to the other, or some math quiz, etc.).

but up to you

**Comment by andreaskoepf** [comment]
> It may be worth to think about always considering a set of languages, instead of only one, i.e. a user could ask for a task in either of their languages, and a task could be appropriate for either of two languages (i.e. translate from one to the other, or some math quiz, etc.).

For task selection that is a future option. For submission of the message I would suggest to use only a single language tag(even when multiple languages are mixed).  When the uses has more than one active language it would be necessary to specify the language used for a submission ... or to use the task's language as default.

Translation is a use-case, but a special one that won't even be solved by using a list of languages, e.g. like instruction: "Translate this text into Chinese:  ..." .. while the instruction-message would be in "en" the task could only be fulfilled by users with "en" + "zh-cn" or similar, so somehow the user would need to specify the desired language of the reply.

I think we should first try the simple solution of 'single language set per session" which will be an improvement for 95% of all use-cases.

**Comment by yk** [comment]
sounds good

**Comment by andreaskoepf** [comment]
link #854

**Pull request merged**
