### PR TITLE
PR: Create notebook to convert r/changemyview data

### PR DESCRIPTION
**Pull request by kayjay-is-here**
you can access the dataset here:
https://huggingface.co/datasets/kjl3080/OA_CMV_Arguments

### CODE REVIEW

**Comment by andrewm4894** [comment]
@kayjay-is-here great - can you:

- [ ] add a open in colab button similar to in the [example notebook](https://github.com/LAION-AI/Open-Assistant/blob/main/notebooks/example/example.ipynb).
- [ ] run all cells so users can see expected sort of output when just reading the notebook in github.

**Comment by kayjay-is-here** [comment]
I need to make some additional changes before PR

**Comment by kayjay-is-here** [comment]
I'm stupid and didn't read the note about the "open in collab" button

**Comment by andreaskoepf** [comment]
@yk this pr contains a 500kb parquet file. Should the parquet file be stored at HF and only the notebook here?

**Comment by kayjay-is-here** [comment]
I think a 500kb one should be stored here as a test set, and the full one is stored on HF. I can remove it if you think that it's not a good idea.

**Comment by yk** [comment]
any chance we can get it down to like 10 or 50kb? if not, it's still fine, but if it's possible to make it very small, it would save a bit of time of everyone doing `git clone`

**Comment by kayjay-is-here** [comment]
No, but I can take the parquet file out if you want

**Comment by andrewm4894** [comment]
@kayjay-is-here can you limit this to printing top 5 or so just so the wall of text is not so big for someone just browsing it on GH: 
image

**Comment by andrewm4894** [comment]
@kayjay-is-here since `output. Parquet` is created by the notebook i think you can just remove it from this PR as not really needed to get the notebook to run from what i can see. 

So i think its just:

- [ ] only print 5 samples of `original_post_train`
- [ ] remove `output.parquet` file from the PR since last couple of cells will generate it anyway for the user. .

**Review by andrewm4894 — CHANGES_REQUESTED** [review]
@kayjay-is-here since `output.parquet` is created by the notebook i think you can just remove it from this PR as not really needed to get the notebook to run from what i can see. 

So i think its just:

- [ ] only print 5 samples of `original_post_train`
- [ ] remove `output.parquet` file from the PR since last couple of cells will generate it anyway for the user.

**Comment by andrewm4894** [comment]
@kayjay-is-here can you trim and reduce all the walls of text produced by any cells. The notebook is 1.4mb in size and won't actually render on my phone on GitHub since so much text. 

I'd suggest add some control like just printing 5 or a small sample of the data to any cell that prints lots of text as output.

**Review by andrewm4894 — APPROVED** [review]

**Pull request merged**
