### PR TITLE
Added French Locale

### PR DESCRIPTION
**Pull request by ParisNeo**
Hi there,
I am From France.
And I find that your project is excellent. I want to help.

The first thing I could do is help adding French language to the web UI.
Please consider accepting this pull request.

I have many other ideas that I can help with like systematically translate all prompts and responses written in all languages to all other languages which will increase the overall throughput.

We can use whisper from open ai (https://github.com/openai/whisper) and add it to the workflow.

One thing at a time. For now I just added french to the ui.

### CODE REVIEW

**Review by AbdBarho — APPROVED** [review]
Thanks!

> I have many other ideas that I can help with like systematically translate all prompts and responses written in all languages to all other languages which will increase the overall throughput.
We can use whisper from open ai (https://github.com/openai/whisper) and add it to the workflow.

Please create an issue describing what you want to achieve, the team has many plans and we can see where this fits.

**Comment by ZiggerZZ** [comment]
Need any help here? I'm a French speaker

**Comment by ParisNeo** [comment]
Hi,

I have completed the French Locale and am now waiting for the upgrades to be made to the production branch so that my updates will be visible on the website.

Please let me know if you come across any errors in my translation. You can either make the necessary corrections and submit a pull request or simply send me a message here.

Any assistance would be greatly appreciated.

Best regards.

**Comment by anamani** [comment]
Hey,

I saw a few mistakes but it's not really practical to write them all in here.

Can I do a sort of review/commit on top of your issue in some way?

Best

**Comment by ParisNeo** [comment]
Yes feel free to do that. I may have overseen some thigs.

Just create a fork or sync with the current version of the code if you already have one, update the code (the locales are in website/public/locales), then do a pull request. Make sure your code is well formatted so that the automatic checks gets passed and finally someone should accept your modifications.

Make sure that I havn't already repared the mistakes. As I said, the current prod version is not the last code. I have already made upgrades but you should wait the next. The translation is in json format and some text is fragmented to multiple chanks. When I saw the final output I've noticed that the final meaning is completely different in the context like are you in. It is translated: etes vous dedans ou un truc de ce genre.  Which is a literal translation, it should be Etes vous parant? So yeah. Check out the json files and if you see something I've forgot to update, please feel free to do it.

**Pull request merged**
