### PR TITLE
Cornell movies dialog dataset

### PR DESCRIPTION
**Pull request by shahules786**
Created instruction->answer format examples from Cornell movies dialog dataset as described in https://github.com/LAION-AI/Open-Assistant/issues/1163

### CODE REVIEW

**Comment by olliestanley** [comment]
You'll need to remove the `.ipynb_checkpoints/` directory before we can merge this

**Comment by andrewm4894** [comment]
@shahules786 thanks! - can you add an open in colab button like in here: https://github.com/LAION-AI/Open-Assistant/blob/main/notebooks/example/example.ipynb

would be nice to programmatically download the `movies_lines.txt` file too so was not a manual step but not a biggie. 

IDea being to aim to try have the notebooks be as easy as possible to run in something like a colab notebook where possible.

**Comment by shahules786** [comment]
@andrewm4894 Done. Please check

**Review by andrewm4894 — APPROVED** [review]
Thanks!

**Pull request merged**
