### PR TITLE
dont render image in markdown

### PR DESCRIPTION
**Pull request by notmd**
related #1721

### CODE REVIEW

**Review by rjmacarthy — APPROVED** [review]

**Comment by AbdBarho** [comment]
This PR takes precedence over #1721?

**Comment by notmd** [comment]
@AbdBarho yeah, #1721 because @0x22almostEvil requested it, but Andres request to hide the image completely so I make this. I don't have a strong opinion about the image, it up to you and others

**Comment by AbdBarho** [comment]
What is the behavior if there is an image? will it display as text `alt` or will it display nothing?

**Comment by notmd** [comment]
> What is the behavior if there is an image? will it display as text `alt` or will it display nothing?

It will display nothing, it just skip img tag.

**Review by andreaskoepf — APPROVED** [review]

**Pull request merged**
