### PR TITLE
Unifying the task structure

### PR DESCRIPTION
**Pull request by fozziethebeat**
This moves the existing tasks to a simpler url hierarchy: `/evaluate` and `/create`.  We rename the pages to match the underlying task names in the backend.

Further, this adds some UI layout to the tasks so users can navigate to the home page without struggle and fixes the UI highlighting for the rating task.

### CODE REVIEW

**Comment by AbdBarho** [comment]
would it be simpler to use layouts for the header and footer?

https://nextjs.org/docs/basic-features/layouts

**Comment by fozziethebeat** [comment]
> 

I like that idea.  If this doesn't get reviewed tomorrow I'll add that in.  otherwise I'll add it in another PR.  If you want, could you create some layouts in a separate PR and then I'll use them?

**Comment by AbdBarho** [comment]
I hope we don't end up with a lot of merge conflicts...

I am currently working on #30 (without all of the header / footer stuff), if this branch gets merged first, I can  gladly add the layout in my pr.

**Comment by fozziethebeat** [comment]
> I hope we don't end up with a lot of merge conflicts...
> 
> I am currently working on #30 and #31 (without all of the header / footer stuff), if this branch gets merged first, I can gladly add the layout in my pr.
> 
> could you please assign #30 and #31 to me? maybe also #28 for tracking purposes.

It'll be a good time to test rebase vs merge practices...

Can you make a comment in #30 and #31? I can't seem to assign them to you right now but I will as soon as Github lets me.

**Review by andreaskoepf — APPROVED** [review]
lgtm, ready for merge.

**Pull request merged**
