### PR TITLE
fix bug Open-Assistant #67 : submit form on enter

### PR DESCRIPTION
**Pull request by seyfeddinenecib**
Adding submit of the signup form when clicking "Enter"

### CODE REVIEW

**Comment by yk** [comment]
hey, thanks so much for contributing :)

is there an argument for / against just making this into a form and then handling the submit? it seems like that could be a bit more streamlined than explicitly checking enter.

**Comment by rsandb** [comment]
> hey, thanks so much for contributing :)
> 
> is there an argument for / against just making this into a form and then handling the submit? it seems like that could be a bit more streamlined than explicitly checking enter.

Eventually, users will need to create a username and password so having this as a form would be the best option. I have a page with that in one form; I just haven't committed it yet. For testing though I think it's easier to keep it the way it is, his enter solution just adds a bit more convenience.

**Review by fozziethebeat — CHANGES_REQUESTED** [review]
I agree with Yannic, Rather than a new input, let's make this a proper form which should get us to the same place.

**Comment by yk** [comment]
for reference, you can probably just spy on #68 where I introduce another login form that uses a proper form

**Comment by seyfeddinenecib** [comment]
I implemented the changes.

**Review by fozziethebeat — APPROVED** [review]

**Pull request merged**
