### PR TITLE
Add retry scoring failed message trees CLI command

### LINKED ISSUE #899: Retry scoring of all trees in scoring_failed state via CLI command
Create a new CLI command (e.g. add to [main](https://github.com/LAION-AI/Open-Assistant/blob/cd2e883e9d3eeabf7056eefc91cfaced83a6636d/backend/main.py#L283)) that finds all message trees in `SCORING_FAILED` state (e.g. rows in `message_tree_state` table) and re-runs the scoring algorithm by calling [TreeManager.update_message_ranks()](https://github.com/LAION-AI/Open-Assistant/blob/cd2e883e9d3eeabf7056eefc91cfaced83a6636d/backend/oasst_backend/tree_manager.py#L652). The retry function (that loops over all failed trees) could be added to tree_manager.py.

### PR DESCRIPTION
**Pull request by Vechtomov**
Resolves #899

### CODE REVIEW

**Review by andreaskoepf — APPROVED** [review]
awesome! thanks for the super-fast work.

**Comment by Hoangphucpro96** [comment]
Call shoow baby

**Comment by Hoangphucpro96** [comment]
Gọi điện cho anh nhé baby

**Comment by Hoangphucpro96** [comment]
https://meetup12.com/#/mine

**Comment by Hoangphucpro96** [comment]
diff

**Pull request merged**
