### PR TITLE
Make only leftside draggable for touch devices

### PR DESCRIPTION
**Pull request by mehdi-zibout**
Touch devices users weren't able to scroll easily #1543 
I implemented the solution proposed by [jwstolk](https://github.com/jwstolk) to make only the leftside draggable when using a touch screen.

### CODE REVIEW

**Comment by AbdBarho** [comment]
Thanks! how does this look or work on right to left languages? does it switch positions?

**Comment by mehdi-zibout** [comment]
> Thanks! how does this look or work on right to left languages? does it switch positions?

For now I don't think it does, I'll try to work on it today.

**Review by AbdBarho — APPROVED** [review]
Thanks

**Comment by jwstolk** [comment]
Thanks! it works great on my phone.

**Pull request merged**
