### PR TITLE
[1477] - add voting and reporting api

### PR DESCRIPTION
**Pull request by layterz**
This PR adds api handlers and database models for votes and reports.

Each vote/report has a foriegn key to the message and messages have model level relationships to votes and reports, which are rendered in the api response for messages.

### CODE REVIEW

**Comment by olliestanley** [comment]
Thanks for this PR, Yannic will likely review when he is available. Could you please comment on issue #1477 which will allow us to assign the ticket to you so others know not to take it on? In future it would be great if you could do this when starting a new ticket also :)

**Comment by layterz** [comment]
Sorry, just added the PR link to that ticket.

**Comment by olliestanley** [comment]
> Sorry, just added the PR link to that ticket.

Thank you! I have assigned the ticket to you

**Comment by yk** [comment]
sorry for being late on this and thank you so much! I've fiddled around quite a bit with the auth, and @olliestanley cleaned up the code a bit, so this will likely have lots of conflicts. I will solve these later, so nothing to do for you.

**Review by yk — APPROVED** [review]

**Pull request merged**
