### PR TITLE
add Basque language support

### PR DESCRIPTION
**Pull request by juletx**
Add Basque (eu) language support

### CODE REVIEW

**Review by AbdBarho — APPROVED** [review]
Thanks!

**Comment by juletx** [comment]
Why are tests failing?

**Comment by fozziethebeat** [comment]
> Why are tests failing?

I don't see any obvious explanation.  Can you first merge main in and resolve the conflicting file?

**Comment by juletx** [comment]
Tests are still failing.

**Comment by juletx** [comment]
> > Why are tests failing?
> 
> I don't see any obvious explanation. Can you first merge main in and resolve the conflicting file?

I've merged main again. I still have no idea why tests are failing.

**Comment by AbdBarho** [comment]
The problem here is very weird:
```
Text content did not match. Server: "Euskara" Client: "Basque"
```
both are correct, I am not sure what should be updated.

**Comment by juletx** [comment]
> The problem here is very weird:
> 
> ```
> Text content did not match. Server: "Euskara" Client: "Basque"
> ```
> 
> both are correct, I am not sure what should be updated.

Yes, very weird. As far as I know, it has only happened with Basque. Apparently, it is a hydration issue, but I have no idea why it happens and how we can solve it.

For now, I have added the translations that were missing.

**Review by fozziethebeat — APPROVED** [review]
I have no idea what fixed the tests but this works so I'm merging now! thank you~

**Comment by fozziethebeat** [comment]
Spoke too soon.  Need to figure out what's going on here...

**Comment by fozziethebeat** [comment]
Alright, I tested this locally.  It seems the test failure happens even without the language code addition.  I'm going to merge this and hope for the best.

**Comment by juletx** [comment]
Seems to be working correctly. However, there is a mistake in the language selection menu. "Eurakasa" is wrong, it should be "Euskara".

**Pull request merged**
