### PR TITLE
Add: Hide All Chat Button

### PR DESCRIPTION
**Pull request by CertifiedJoon**
Fixes: #3287

I have added Hide All Chat Button as specified at #3287 
image
image

### CODE REVIEW

**Comment by CertifiedJoon** [comment]
CI issue has been resolved. ready for review.

**Comment by olliestanley** [comment]
@CertifiedJoon did you mean to close this?

**Comment by CertifiedJoon** [comment]
@olliestanley yup posted a new one. Sorry for the confusion.

**Comment by someone13574** [comment]
> @ olliestanley yup posted a new one. Sorry for the confusion. I had touched package.json file somehow and linter wouldn't allow me to change it back.

In the future you can just force-push to the same remote branch and it will overwrite the changes in the PR.

**Pull request closed without merging**
