### PR TITLE
Add Similarity functions to utils

### PR DESCRIPTION
**Pull request by danielpatrickhug**
This PR adds cosine similarity and euclidean distance functions for HF embeddings.

- Adds a new file to backend/oasst_backend/utils named similarity_functions.py
- implements functions in NumPy
- ran pre-commit checks

### CODE REVIEW

**Review by yk — APPROVED** [review]
looks good, but maybe some type hints would help

**Comment by danielpatrickhug** [comment]
@yk Hey, I added the typing as specified in the MessageEmbedding model and added a ZeroDivision error in cosine similarity in the case some one passes in a list of zeros

**Comment by andrewm4894** [comment]
@danielpatrickhug i looks like this is changing 74 files for some reason - are you able to update your feature branch from upstream/main perhaps.

**Comment by danielpatrickhug** [comment]
@andrewm4894 yeah, I see that as well I'm not entirely sure what I'm doing to make that happen. I'm following the commands for contribution.md. will fix

**Comment by danielpatrickhug** [comment]
new PR here #633

**Pull request closed without merging**
