### PR TITLE
commented links

### PR DESCRIPTION
**Pull request by AAYUSH-droid**
Commented links to solve issue #139.

### CODE REVIEW

**Comment by AbdBarho** [comment]
@AAYUSH-droid thank you

Please comment out the entire `TaskOption` not just the url, but only for summerize story & rate summary as specified in #139

**Review by AbdBarho — CHANGES_REQUESTED** [review]
Please comment out the entire `TaskOption` not just the url, but only for summerize story & rate summary as specified in #139

**Comment by AAYUSH-droid** [comment]
alright @AbdBarho I'll link a new PR.

**Comment by AAYUSH-droid** [comment]
#147 made changes

**Pull request merged**
