### PR TITLE
added clear list for more understanding of result

### PR DESCRIPTION
**Pull request by chandru1003**
changes are done by me
  - added one comment
 - added clear() to list instructions
          - which does not your output but every time I ran value gets appended to the list so it makes it confusing to understand so clear list after printing the list, now only output/value **gets** appended to the list which line ran.
- import random in fist cell because it throwing error for me

### CODE REVIEW

**Comment by yk** [comment]
@Graverman-dev could you give your input here?

**Comment by GravermanDev** [comment]
well I looked at the file and I cannot find any changes besides one comment, unless I missed something @chandru1003. You can merge because the comment is okay but I don't see any differences like at all

**Comment by yk** [comment]
@chandru1003 could you explain a bit what you've changed?

**Comment by chandru1003** [comment]
> @Graverman-dev could you give your input here?
when you ran any other cell it is added to the list and  makes clutter 
Fix structure errors in this essay
Fix grammar errors in this essay
Fix typing errors in this essay
Fix typing errors in this essay
Fix grammar errors in this essay

if we clear the list, the output will 
run 1
   Fix structure errors in this essay
   Fix grammar errors in this essay
   Fix typing errors in this essay
run 2
  Fix typing errors in this essay

**Comment by chandru1003** [comment]
> changes are done by me
> 
> * added one comment
> * added clear() to list instructions
>   - which does not your output but every time I ran value gets appended to the list so it makes it confusing to understand so clear list after printing the list, now only output/value **gets** appended to the list which line ran.
> * import random in fist cell because it throwing error for me



> well I looked at the file and I cannot find any changes besides one comment, unless I missed something @chandru1003. You can merge because the comment is okay but I don't see any differences like at all

changes are done by me

added one comment
added clear() to list instructions
- which does not your output but every time I ran value gets appended to the list so it makes it confusing to understand so clear list after printing the list, now only output/value gets appended to the list which line ran.
import random in fist cell because it throwing error for me

**Review by yk — APPROVED** [review]

**Pull request merged**
