### PR TITLE
added markdown tooltip

### PR DESCRIPTION
**Pull request by Anantha-Kandrapu**
Issue #1919 

Added a link to markdown syntax docs beside the progress bar :
[https://www.markdownguide.org/basic-syntax]

### CODE REVIEW

**Comment by Anantha-Kandrapu** [comment]
> Thanks, can you provide the screenshot?

image

I can add a label to the tooltip.

**Comment by notmd** [comment]
Can you make a design exactly like GitHub does? And the icon too.
image
Omit the button for now.

**Comment by notmd** [comment]
> > Can you make a design exactly like GitHub does? And the icon too. image Omit the button for now.
> 
> Sure. So I need to add the text `icon + styling with markdown is supported` and put the whole thing below the progress bar. right?

Put to bottom it with `position: "absolute"` to the textarea. Just like Github does

**Comment by Anantha-Kandrapu** [comment]
> > > Can you make a design exactly like GitHub does? And the icon too. image Omit the button for now.
> > 
> > 
> > Sure. So I need to add the text `icon + styling with markdown is supported` and put the whole thing below the progress bar. right?
> 
> Put to bottom it with `position: "absolute"` to the textarea. Just like Github does

new

Is this good?

**Review by notmd — APPROVED** [review]
Thanks, lgtm

**Comment by notmd** [comment]
> Thanks, lgtm

It's not related. @Anantha-Kandrapu is there any reason why you update the yarn.lock file? If not can you revert the change?

**Comment by Anantha-Kandrapu** [comment]
> > How come this changes the `yarn.lock` in the `docs` part of the project? Is that related to the website?
> 
> It's not related. @Anantha-Kandrapu is there any reason why you update the yarn.lock file? If not can you revert the change?

I reverted the change by deleting the file in my local , downloading from OA main and pasting it.
Is there a better way to do this?

**Review by notmd — APPROVED** [review]

**Pull request merged**
