### PR TITLE
Slightly better README.md

### PR DESCRIPTION
**Pull request by MohamedAliRashad**
My take on the simplicity of experiencing the project

### CODE REVIEW

**Review by ericsomto — CHANGES_REQUESTED** [review]
Address readme before merging

**Review by yk — COMMENTED** [review]
thank you very much. I've just made #123 which might conflict with this one.

while we are improving, do you think you could also remove the period between the first two sentences and add a comma?

**Comment by MohamedAliRashad** [comment]
@yk I fixed what you ask

**Comment by yk** [comment]
thank you :) now just resolve the merge conflicts then we're perfect

**Comment by yk** [comment]
Thank you! We don't need the email link thing anymore, but I can remove that later. Small improvements like this really make the experience better for newcomers :)

**Review by yk — APPROVED** [review]

**Pull request merged**
