### PR TITLE
SFT training

### PR DESCRIPTION
**Pull request by sanagno**
Base code for SFT pretraining. Currently, it is mostly a placeholder code. Will be adapted based on the format of the human generated data.

### CODE REVIEW

**Review by yk — APPROVED** [review]
thank you, lgtm

**Comment by sanagno** [comment]
That would be great, I am already looking into this but feel free to start with the PR.

**Comment by mrcabbage972** [comment]
Cool, I'll work on this during the weekend.

**Comment by sanagno** [comment]
@mrcabbage972 see also the latest PR #452 and #456.

Feel free to edit.

**Comment by mrcabbage972** [comment]
I see that @theblackcat102 already started working on 8-bit quantization in #456.

**Pull request merged**
