### PR TITLE
updated sponser's list #2898

### PR DESCRIPTION
**Pull request by dewasahu2003**
update the team list and added evobits

### CODE REVIEW

**Comment by olliestanley** [comment]
Hi, thanks for this PR! Would you be able to resolve the formatting issues causing the pre-commit check to fail?

**Comment by dewasahu2003** [comment]
sure

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dewasahu2003** [comment]
Screenshot 2023-04-25 222850


--locally all pre-commit are passed

**Comment by olliestanley** [comment]
It looks like the remaining pre-commit fails are to do with changes to `package-lock.json`. Maybe you could just remove changes to that file from this PR as it shouldn't need to be updated

**Review by AbdBarho — APPROVED** [review]

**Pull request merged**
