### PR TITLE
Create data_augment.py

### PR DESCRIPTION
**Pull request by finitearth**
Converted the data_augmentation files from the notebooks. https://github.com/LAION-AI/Open-Assistant/issues/460

### CODE REVIEW

**Comment by finitearth** [comment]
grafik
Unfortunately I keep getting this weird error when running "pre-commit" :/ Has anyone ever ancountered this issue?

**Comment by yk** [comment]
could you try using python3.10?

**Comment by finitearth** [comment]
> could you try using python3.10?

grafik

error remains the same :/

**Comment by yk** [comment]
@finitearth did you mean to close this on purpose?

**Pull request closed without merging**
