### PR TITLE
Use a provider for client env

### PR DESCRIPTION
**Pull request by AbdBarho**
Probably the most consistent way of providing config to the app.

Easily extensible, well understood, no side effects, and not fragile.

A lot of changes are just renaming.

Closes #2334

### CODE REVIEW

**Comment by notmd** [comment]
I believe this doesn't work, NextJs still use the static env var. However, the new API is much safe than the current one.

**Comment by AbdBarho** [comment]
> I believe this doesn't work, NextJs still use the static env var. However, the new API is much safe than the current one.

🤦‍♂️ you are right, when I tried it with `npm run build` it worked, when I ran it from docker it did not work.


Can we just say fuck it and add `/api/config` which returns the config as json?

**Comment by notmd** [comment]
I got a working version now (hopefully). Will update my PR in a few minutes.

**Comment by notmd** [comment]
@AbdBarho can this be closed now?

**Comment by AbdBarho** [comment]
> @AbdBarho can this be closed now?

yeah true

**Pull request closed without merging**
