### PR TITLE
Writing prompt

### PR DESCRIPTION
**Pull request by fabraz**
This PR deliveries the code used to sample writing prompt dataset, which can be downloaded at https://huggingface.co/datasets/fabraz/writingPromptAug.

### CODE REVIEW

**Comment by andrewm4894** [comment]
@fabraz thanks!

can you add a readme in the folder and a open in colab button to the notebook. 

Idea being someone can quickly scan the readme and then just open the notebook in Google colab even if they want to start playing with it.

https://github.com/LAION-AI/Open-Assistant/tree/main/notebooks/example

**Comment by fabraz** [comment]
> @fabraz thanks!
> 
> can you add a readme in the folder and a open in colab button to the notebook.
> 
> Idea being someone can quickly scan the readme and then just open the notebook in Google colab even if they want to start playing with it.
> 
> https://github.com/LAION-AI/Open-Assistant/tree/main/notebooks/example

@andrewm4894, I just realized that this notebook would be better located under [data-augmentation](https://github.com/LAION-AI/Open-Assistant/tree/main/notebooks/data-augmentation). Do you agree?

**Comment by andrewm4894** [comment]
Yep, maybe so. Kinda a lot of stuff ending up under data augmentation since it is very general but makes sense. Am sure some stage down the road we might reorder things in various ways but happy to keep it fairly organic for now. 

So yep, maybe makes sense to add under data augmentation for consistency as of now.

**Comment by fabraz** [comment]
Colab button and README.md cleared.

**Comment by andrewm4894** [comment]
notebook is looking a bit funny for some reason

seems like maybe some code cells and markdown getting messed up - is it just me? 

https://github.com/fabraz/Open-Assistant/blob/writing_prompt/notebooks/data-augmentation/writing-prompt/writing_prompt.ipynb

image

**Comment by fabraz** [comment]
So weird. It seems that it converted all the cells into a single one. Checking …

**Comment by fabraz** [comment]
@andrewm4894, I've found that the messy jupyter was due to a GitHub bug. When GH renders the following code, it lost any jupyter style setting thereafter.

image

I made some changes in the code, and now GH managed to present it correctly. Check it out.

I've done many commits for troubleshooting purposes. Let me know if it would be better to open another PR, to get rid of this commit messy history.

**Comment by andrewm4894** [comment]
oh interesting - ive seen markdown cells break github rendering before but never code cells lol

**Comment by andrewm4894** [comment]
i'm confused a bit by this - is that your gh username - im not sure if meant to be there or not? 

image

**Comment by andrewm4894** [comment]
i also see an error so not all cells are rendered 

ideally the notebooks would be a clean run top to bottom with all cells rendered so interested users can just read it before deciding if they want to play with it. 

image

**Comment by fabraz** [comment]
@andrewm4894 I removed unnecessary comments and fixed the cell with error output. Check, please!

**Review by andrewm4894 — APPROVED** [review]

**Comment by olliestanley** [comment]
This should have had the `.ipynb_checkpoints` dir removed before merge really. Ah well

**Comment by andrewm4894** [comment]
https://github.com/LAION-AI/Open-Assistant/pull/1358

Waiting to merge this

**Pull request merged**
