### PR TITLE
Notebook to convert the DIVERSE dataset

### PR DESCRIPTION
**Pull request by ThierryDeruyttere**
In this pull request I include a notebook to:

- 1: Download the DIVERSE dataset with a git pull
- 2: Transform the data to the Open-Assistant format.

This is a proposed solution for #746.

### CODE REVIEW

**Comment by andrewm4894** [comment]
@ThierryDeruyttere thanks! can you:

- [ ] add colab button to top of the notebook (see [example notebook](https://github.com/LAION-AI/Open-Assistant/blob/main/notebooks/example/example.ipynb) that can use as example).
- [ ] get pre-commit passing - i can help if needed, if can be a bit annoying :)
- [ ] restart and run all cells in the notebook so someone browsing on GitHub can see some expected outputs without having to fire it up themselves.

Just let me know if need any help on any of these and i'd be happy to help.

**Comment by andrewm4894** [comment]
(oh i see pre-commit passing - checking that box above :) )

**Comment by ThierryDeruyttere** [comment]
Hi @andrewm4894!

All your remarks should be resolved now. 
I also added some more prints to make it more clear to the people on GitHub what the resulting data looks like.
If there are any problems left, let me know!

**Review by andrewm4894 — APPROVED** [review]
Thanks!

**Comment by Rallio67** [comment]
There are some problems with this dataset. The data contains a lot of factual errors and there is a very high degree of duplication (perhaps a parsing/downloading error). Check discord for more discussion on this. The underlying human generated data from AI2 is of very high quality though and definitely would like to incorporate that somehow.

https://allenai.org/data/strategyqa](https://allenai.org/data/strategyqa

**Pull request merged**
