### PR TITLE
Fixed some capitalisation in headers in readme

### PR DESCRIPTION
**Pull request by sryu1**

### CODE REVIEW

**Review by andreaskoepf — COMMENTED** [review]
I personally don't think this is necessary, maybe a native speaker could comment.

**Comment by sryu1** [comment]
> I personally don't think this is necessary, maybe a native speaker could comment.

I am a native speaker...

**Comment by andrewm4894** [comment]
Not sure it makes sense to capitalize like that. Some people maybe prefer it based on personal preferences but i don't think it's common enough practice for an open source project like this.

**Comment by sryu1** [comment]
Yeah, good point, I may have been a bit biased xD

**Comment by sryu1** [comment]
Disregard this then.

**Comment by andrewm4894** [comment]
> Yeah, good point, I may have been a bit biased xD

no worries - I've had many an argument with the technical writers where I work over stuff like this lol - funny to be on the other side for once :)

**Pull request closed without merging**
