### PR TITLE
Add Google OAuth support to inference backend

### LINKED ISSUE #1790: Add additional authentication methods to generate JWT on inference server
As #1772 is merged and users exist in the inference server database and can be authenticated via Discord OAuth2, we need to add email authentication. We should also discuss other authentication providers (e.g. GitHub)

Individual additional providers can have their own issues made to split this up further

### PR DESCRIPTION
**Pull request by olliestanley**
This will round out our auth options alongside Discord and GitHub. I think these should be sufficient for us to close #1790.

### CODE REVIEW

**Comment by olliestanley** [comment]
I haven't tested this locally yet as I need to setup a Google OAuth app but marking ready for review for any code comments

**Comment by AbdBarho** [comment]
> I haven't tested this locally yet as I need to setup a Google OAuth app but marking ready for review for any code comments

is this ready now?

**Comment by olliestanley** [comment]
> is this ready now?

I think so. I think it could be cleaner but I won't have time to make changes for a couple of days so I will address it as part of #2286 with the other auth code

**Review by AbdBarho — APPROVED** [review]
The google api seems a bit weird to me. "People"?

**Comment by olliestanley** [comment]
> The google api seems a bit weird to me. "People"?

Yeah it's odd. Maybe comes from the Google+ days. They also make the OAuth process a lot less clear than other providers!

**Pull request merged**
