### PR TITLE
1442: Add option to export labels of exported messages to a separate JSONL file

### LINKED ISSUE #1442: Add to export script the ability to export flagged/deleted messages with message labels

### PR DESCRIPTION
**Pull request by olliestanley**
Resolves #1442

### CODE REVIEW

**Comment by SummerSigh** [comment]
Why does the safety label export need to go a seperate jsonl file? is it possible to export it with the rest of the data in the current jsonl file?

**Comment by olliestanley** [comment]
> Why does the safety label export need to go a seperate jsonl file? is it possible to export it with the rest of the data in the current jsonl file? It would simplify data processing and be less error prone if the labels are co-located with the data.

It would be possible to export to the same file with some changes to the code. I can modify this tomorrow if it would be more useful

**Comment by SummerSigh** [comment]
that would be much appreciated! Thanks!

**Comment by olliestanley** [comment]
> that would be much appreciated! Thanks!

In the latest version labels will be included in the export file. Just need Andreas to review this and then we can start exporting labelled messages.

**Comment by SummerSigh** [comment]
Thank you!

**Review by andreaskoepf — APPROVED** [review]

**Pull request merged**
