### PR TITLE
Devcontainer improvements

### PR DESCRIPTION
**Pull request by andrewm4894**
playing around with similar idea to this PR. https://github.com/LAION-AI/Open-Assistant/pull/327

changes:
- make devcontainer more generic as opposed to launching into any specific service.
- add readme to .devcontainer folder with some example usage.
- ensure `pre-commit` is installed and available in dev container.
- validate that `docker compose up --build` works from within the codespace.

### CODE REVIEW

**Comment by andrewm4894** [comment]
image

**Comment by andrewm4894** [comment]
image

**Comment by yk** [comment]
hey this is awesome. do you think you could also tell people about this in the main README? or at least drop a hint there with a link to the readme you wrote?

**Comment by andrewm4894** [comment]
> hey this is awesome. do you think you could also tell people about this in the main README? or at least drop a hint there with a link to the readme you wrote?

yep will do, will add a one liner and link. just was hesitant to add too much myself into the main readme but agree makes sense to reference it - will do in a few mins

**Comment by andrewm4894** [comment]
@yk done

**Review by yk — APPROVED** [review]
awesome, thank you!

**Pull request merged**
