### PR TITLE
rename openassistant/ -> data/

### PR DESCRIPTION
**Pull request by andreaskoepf**
This PR renames the `openassistant/` folder to `data/`. I think the original folder name caused a lot of confusion and this change was long overdue.

### CODE REVIEW

**Review by olliestanley — APPROVED** [review]
I agree with this change. Would it make sense to also add a `data/` section to the code owners file for this going forwards?

**Comment by andreaskoepf** [comment]
> I agree with this change. Would it make sense to also add a `data/` section to the code owners file for this going forwards?

Yes, I also looked at CODEOWNERS and was a bit shocked to see that no-one was responsible for the old openassistant folder. We clearly have to revamp/reorganize the dataset collection efforts. I would nominate @Vechtomov, @bitplane & @ontocord as initial code-owners for `data/`.

**Comment by olliestanley** [comment]
Looks like the code owners file won't recognise Vechtomov - does he have write access to the repo?

**Comment by andreaskoepf** [comment]
> Looks like the code owners file won't recognise Vechtomov - does he have write access to the repo?

I have just sent him an invitation.

**Comment by andrewm4894** [comment]
we could do with adding a README.md to /data maybe - will see if i can do this

**Pull request merged**
