### PR TITLE
Add website translations to Spanish

### PR DESCRIPTION
**Pull request by GuilleHoardings**
This translates to Spanish the files in the folder `website/public/locales`.

### CODE REVIEW

**Comment by AbdBarho** [comment]
@GuilleHoardings Thank you, you can delete the files that are still in english.

**Comment by GuilleHoardings** [comment]
@AbdBarho I've translated the two files that were missing. Thank you for the review.

**Review by AbdBarho — APPROVED** [review]

**Comment by AbdBarho** [comment]
@GuilleHoardings thank you, you can find it here: https://web.dev.open-assistant.io/es/dashboard

you can login as a debug user

**Comment by GuilleHoardings** [comment]
Thank you for the merge. I had already tested it locally. I see that there are sentences that are not translated (like "Top 5 Contributors Today") because they are not internationalized in the source code. Should I work on that or is there any reason for it or somebody working on it?

**Comment by AbdBarho** [comment]
no one is working on this, feel free to take it.

**Comment by GuilleHoardings** [comment]
Great. I will try when I have time.

**Pull request merged**
