### PR TITLE
TV and Movie dialogue corpus

### PR DESCRIPTION
**Pull request by sedthh**
A huge collection (2781 texts total) of TV and Movie dialgoues and transcripts either collected or scraped from transcript sites.
See datacard for more information: https://huggingface.co/datasets/sedthh/tv_dialogue

They are in a standardized format ([speaker] speech) and the idea is that these dialogues should help the Assistant to:
1) mimic the style of famous characters
2) generate new episodes of certain shows

NOTE: this is part 1, there will be a part 2 based entirely on ForeverDreaming's transcripts
NOTE2: the notebook only contains the crawler for IMSDb, the parsers for the rest of the sources were omited as they had a low code quality to save time

### CODE REVIEW

**Comment by Vechtomov** [comment]
Can you add other source crawlers and parsers? And also converting to final format. Code quality is not so important as the ability to reproduce data mining.

**Comment by sedthh** [comment]
I can add the converter for the outside sources that need conversion if that's enough.

**Comment by Vechtomov** [comment]
Yes, please add everything you have 🙂

**Review by Vechtomov — APPROVED** [review]
Very cool, thanks!

**Pull request merged**
