### PR TITLE
Added collapsable text for text that's too long

### PR DESCRIPTION
**Pull request by kostiak**
This is a draft PR for #190

### CODE REVIEW

**Review by fozziethebeat — COMMENTED** [review]
Looks solid.  Will approve after merging in the changes from dark mode!

**Comment by kostiak** [comment]
@fozziethebeat As I said in #190, I still have an issue here in that a modal does not take up the full width/height of the screen:
image

I can probably fix it using style tags, but I think there might be a simpler way to fix it that I'm missing. Can you take a look at it on mobile/using the browser mobile emulator?

Thanks.

**Comment by fozziethebeat** [comment]
> @fozziethebeat As I said in #190, I still have an issue here in that a modal does not take up the full width/height of the screen: image
> 
> I can probably fix it using style tags, but I think there might be a simpler way to fix it that I'm missing. Can you take a look at it on mobile/using the browser mobile emulator?
> 
> Thanks.

I tried it out locally and deleted the `Container` in `website/src/components/CollapsableText.tsx`.  That fixed the width issue for me.  Can you try that?

**Comment by kostiak** [comment]
@fozziethebeat 
I tried that. Doesn't seem to fix it for me.

It works correcly on "small" screens, but when I try it in the device emulator:
image

**Comment by kostiak** [comment]
@fozziethebeat 
Hey, fixed the overlay with a style tag for now, this is how it looks on mobile:
image

Let me know what you think.

**Review by fozziethebeat — APPROVED** [review]
I think this is good enough for a first start.  It's functional on mobile although not ideal.  We can iterate later after other things.

**Pull request merged**
