### PR TITLE
Adding a notebook to make use of the TSSB-3M bugs dataset

### PR DESCRIPTION
**Pull request by RiccardoRiglietti**
# [ManySStuBs4J Dataset](https://zenodo.org/record/3653444#.Y-Ywz9LMKV4) 

The ManySStuBs4J corpus is a collection of simple fixes to Java bugs, designed for evaluating program repair techniques. We collect all bug-fixing changes using the SZZ heuristic, and then filter these to obtain a data set of small bug fix changes.

It contains over 3 million bugs, so the benefit from it would be substantial.

It is easy to put it into dialogue form:

User: Find the bug in the following code:
{CODE}
Reply: The bugfix can be described as follows:
{COMMIT_MESSAGE}
The fixed code is:
{FIXED-CODE}

It would be a substantial boost to our dataset as far as code is concerned.

As for now, I create prompts only with broken and fixed code, without commit messages that must be scraped from GitHub. Still it should be very useful.

# Issue link

https://github.com/LAION-AI/Open-Assistant/issues/1395

# Notebook on Colab

Here is the Google Colab code to generate the prompts from the dataset: https://colab.research.google.com/drive/16Fr4iW0x1JdPC8x6GiBb6b4YtEr1CDGH?authuser=4#scrollTo=GFt0SJ1vpMPR

I also added it into the notebooks folder.

## Contributing

Adding a way to incorporate commit messages into the prompts would be a great contribution. This can be done by scraping the GitHub API for the commit messages based on the commit hash, or by downloading the repository with the full history and extracting the commit messages from there.

### CODE REVIEW

**Comment by RiccardoRiglietti** [comment]
I have run the black formatter on the notebook, why does it still say pre-commit failed?

**Comment by RiccardoRiglietti** [comment]
Now I have run the pre-commit script and the check passes.

**Comment by olliestanley** [comment]
Hi @RiccardoRiglietti, would you like this to be considered for merging now or to wait until the "to do" comment in the notebook regarding commit messages is worked on as well?

**Comment by RiccardoRiglietti** [comment]
@olliestanley Given that the commits are not in the dataset, but they must be taken from GitHub with the API or web scraping or cloning the repositories with their history, so it is a large amount of work (also considering limited API quotas). In my opinion the pairs of wrong/correct code already represent a good addition to the training data, as there are over 3 million such pairs, so I think it is best to ask to be considered for merging now. As far as what is the progress of adding commits messages, you could ask @zirui that mentioned that he started working on this at https://github.com/LAION-AI/Open-Assistant/issues/1395

**Comment by olliestanley** [comment]
> @olliestanley Given that the commits are not in the dataset, but they must be taken from GitHub with the API or web scraping or cloning the repositories with their history, so it is a large amount of work (also considering limited API quotas). In my opinion the pairs of wrong/correct code already represent a good addition to the training data, as there are over 3 million such pairs, so I think it is best to ask to be considered for merging now. As far as what is the progress of adding commits messages, you could ask @zirui that mentioned that he started working on this at #1395

Ok great! Could you add a [Open in Colab] sticker to the top of the notebook, as in the other notebooks in the repo, e.g. [here](https://github.com/LAION-AI/Open-Assistant/blob/main/notebooks/data-augmentation/essay-revision/essay-revision.ipynb)? And maybe delete the empty cell at the end with outdated output? Then I think we can merge this

**Comment by RiccardoRiglietti** [comment]
@olliestanley I cleaned up the notebook, removed the outdated cell, added the open in colab badge, added section titles and a short description at the start.

**Comment by olliestanley** [comment]
> @olliestanley I cleaned up the notebook, removed the outdated cell, added the open in colab badge, added section titles and a short description at the start.

Thanks! Looks like the Colab link still points to the essay revision dataset, so it will need to be tweaked to point to the path your notebook will be at once it's merged. After that I think this will be ready, I'm off to bed now so will confirm it tomorrow :)

**Comment by RiccardoRiglietti** [comment]
@olliestanley I put the link temporarily to the online version of the notebook, good night.

**Review by olliestanley — APPROVED** [review]
Thank you!

**Pull request merged**
