### PR TITLE
Update devcontainers

### PR DESCRIPTION
**Pull request by andrewm4894**
add docker extension to devcontainers by default

(avoids having to manually install docker extension when want to interact with containers from vscode when working in a devcontainer)

### CODE REVIEW

**Comment by bitplane** [comment]
Looks good to me.

**Review by bitplane — APPROVED** [review]

**Comment by andrewm4894** [comment]
Marking as draft until I fix conflicts

**Comment by bitplane** [comment]
Sorry mate I tried to fix the merge conflicts in the web UI as they were my conflicts, but it turns out I should never actually do this because, well, look at the mess I made!

**Comment by andrewm4894** [comment]
I'll close this and do a fresh one again at some stage if it's not added by additional updates to devcontainers in meantime.

**Pull request closed without merging**
