### PR TITLE
Add timeout to requests calls

### PR DESCRIPTION
**Pull request by pixeeai**
Many developers will be surprised to learn that `requests` library calls do not include timeouts by default. This means that an attempted request could hang indefinitely if no connection is established or if no data is received from the server. 

The [requests documentation](https://requests.readthedocs.io/en/latest/user/advanced/#timeouts) suggests that most calls should explicitly include a `timeout` parameter. This codemod adds a default timeout value in order to set an upper bound on connection times and ensure that requests connect or fail in a timely manner. This value also ensures the connection will timeout if the server does not respond with data within a reasonable amount of time. 

While timeout values will be application dependent, we believe that this codemod adds a reasonable default that serves as an appropriate ceiling for most situations. 

Our changes look like the following:
```diff
 import requests
 
- requests.get("http://example.com")
+ requests.get("http://example.com", timeout=60)
```

<details>
  <summary>More reading</summary>

  * [https://docs.python-requests.org/en/master/user/quickstart/#timeouts](https://docs.python-requests.org/en/master/user/quickstart/#timeouts)
</details>

Powered by: [pixeebot](https://docs.pixee.ai/) (codemod ID: [pixee:python/add-requests-timeouts](https://docs.pixee.ai/codemods/python/pixee_python_add-requests-timeouts))

### CODE REVIEW

**Comment by pixeeai** [comment]
FYI - This change was autogenerated from a GitHub app - called [Pixeebot](https://github.com/marketplace/pixeebot-automated-code-fixes). A code-quality GitHub App; like Dependabot, but for source code. Feel free to check it our for more details for how you can install it onto your project's repo for continued code hardening and code security recommendations.

**Comment by pixeeai** [comment]
Any chance you've had the time to review these changes?

If you're not interested implementing them at this time, no worries. I can close the PR and follow up with additional changes in the future. Also, this plugin is free for non-commercial open sourced projects, so feel free to give it an install if you want to see the other recommended PRs. ([GitHub Apps - pixeebot](https://github.com/apps/pixeebot))

Thanks,
Zach

**Comment by x64x2** [comment]
Stop Contributing, Project been dead for months now

**Comment by bitplane** [comment]
@pixeeai Please inform your owner that they should not blindly change random functions in machine learning projects. secure random number generators add nothing but overhead, and where the previous generator was used with a known seed, you risk messing up the training and test data splits.

**Comment by pixeeai** [comment]
> Stop Contributing, Project been dead for months now

Apologies, was not aware it was the development has paused.

Thanks,
Zach

**Comment by pixeeai** [comment]
> @pixeeai Please inform your owner that they should not blindly change random functions in machine learning projects. secure random number generators add nothing but overhead, and where the previous generator was used with a known seed, you risk messing up the training and test data splits.

Apologies as well, the intended changes were specifically for adding timeout values to the requests. Did not mean to pull in the other changes regarding the random number generator.

This is what it was intended to be pulled from:
https://github.com/Pixee-Bot-Python/Open-Assistant/pull/5/files

Sorry again!

Take care,
Zach

**Pull request closed without merging**
