### PR TITLE
Add `inlang` to make the contribution of translations easier

### PR DESCRIPTION
**Pull request by NiklasBuchfink**
## Description

This PR add the `inlang.config.js` and `@inlang/cli` to Open-Assistant to solve the issue #3077 

With these changes, translators can manage translations in a no-code web editor and useful linting rules and machine translations can be used within the editor or via the `@inlang/cli`.

I added a badge with the current translation status and a short description to the contribution guidelines.

### Preview

**Editor**
A live instance of the editor can be previewed with the following link:
https://inlang.com/editor/github.com/NiklasBuchfink/Open-Assistant

**Badge**
[translation badge](https://inlang.com/editor/github.com/NiklasBuchfink/Open-Assistant?ref=badge)

## Further information

To check the status of the translations, exece `npx inlang lint`. Other useful command like `machine translate` and `open editor` your can find in the [docs](https://inlang.com/documentation/apps/inlang-cli).

Within this week, the inlang VS code extension should also work ootb for `i18next` projects and helps extract messages and display inline annotations.

### CODE REVIEW

**Comment by NiklasBuchfink** [comment]
@olliestanley Currently this is not supported. I have created an issue for this case, as we will continue to encounter this problem. We discuss this today. Feel free to join the conversation.

See https://github.com/inlang/inlang/issues/919

**Comment by samuelstroschein** [comment]
@NiklasBuchfink You made a mistake while installing the CLI. There is no need for the package.json files and modified .gitignore. Install the CLI as part of the website, not at the root of the repo instead. 

@olliestanley Are you okay with having the inlang.config.js at the root? Supporting nested directories would be a large burden to implement correctly in every app.

**Comment by olliestanley** [comment]
> @olliestanley Are you okay with having the inlang.config.js at the root? Supporting nested directories would be a large burden to implement correctly in every app.

I think this might be fine if it's only the `inlang.config.js` file. Will wait for the web team to confirm though

**Comment by NiklasBuchfink** [comment]
We are working on the issue mentioned about the CLI working in subdirectories with a flag. I will inform you as soon as the problem is fixed.

**Review by notmd — APPROVED** [review]
Thanks

**Review by andreaskoepf — APPROVED** [review]

**Comment by felixhaeberle** [comment]
@olliestanley would you also like to see inlang GitHub Actions?

Providing you with current CLI functionality (lints, machine translate, more soon) but at the convenience of a GitHub Action?

- simple to integrate, just a few lines.
- lints your translations, fits perfectly in your [built frontend workflow](https://github.com/LAION-AI/Open-Assistant/blob/main/.github/workflows/build-frontend.yaml).
- can automatically create (or comment in) PR's when something broke & auto-fix?

We are currently looking for projects interested in this and would build it for you if you simply say "Yes" :)

**Pull request merged**
