### PR TITLE
add dataset research papers

### PR DESCRIPTION
**Pull request by falahgs**
add dataset research papers

### CODE REVIEW

**Comment by falahgs** [comment]
[dataset]([url](https://huggingface.co/datasets/Falah/research_paper2023))
Research Paper Dataset 2023
Dataset Information:
The "Research Paper Dataset 2023" contains information related to research papers. It includes the following features:
Title (dtype: string): The title of the research paper.
Abstract (dtype: string): The abstract of the research paper.

**Review by andreaskoepf — APPROVED** [review]
wow, very nice. Thank you!

**Comment by andreaskoepf** [comment]
@falahgs could you run pre-commit to normalize the formatting please? thx

**Comment by falahgs** [comment]
> 
Yes done pre-commit

**Comment by olliestanley** [comment]
Closing this as I believe it's superseded by #3596. Let me know if that is not correct

**Pull request closed without merging**
