### PR TITLE
feat: Add support for rendering LaTeX inside of markdown

### PR DESCRIPTION
**Pull request by DominiqueGarmier**
### Addend support for rendering LaTeX inside of markdown using [remark-math](https://github.com/remarkjs/remark-math) (and rehype-katex).

Security: As per [remark-math](https://github.com/remarkjs/remark-math#security)
> Using `rehype-katex` or `rehype-mathjax` should be safe assuming that you trust
KaTeX and MathJax.
Any vulnerability in them could open you to a [cross-site scripting (XSS)][xss]
attack.
See their readmes for more info.

Testing: `npm run dev` works fine and the component does what is expected (I haven't written any tests)

Related Issue: https://github.com/LAION-AI/Open-Assistant/issues/2588

### CODE REVIEW

**Comment by notmd** [comment]
Thank you, how much the bundle size is affected by this change?

**Comment by DominiqueGarmier** [comment]
Current bundlesize of [main](https://github.com/LAION-AI/Open-Assistant/actions/runs/4717680282/jobs/8366526323#step:6:119): `chunks/webpack-a6924315898141db.js     8.24 kB`
this [commit](https://github.com/LAION-AI/Open-Assistant/actions/runs/4713030966/jobs/8359800223?pr=2592#step:6:119):  `chunks/webpack-eec6f8648a4a9dfb.js     8.63 kB`

I assume that current main and my upstream haven't changed in bundlesize.

**Review by notmd — APPROVED** [review]
Thanks

**Comment by DominiqueGarmier** [comment]
it's not in production yet should be in 0.0.2-beta10

**Comment by leowalkling** [comment]
Ah of course. Thanks!

**Pull request merged**
