### PR TITLE
Dashboard Integration

### PR DESCRIPTION
**Pull request by rsandb**

### CODE REVIEW

**Comment by rsandb** [comment]
Not sure why createMockRouter.ts fails the build test. Haven't even touched that file

**Comment by rsandb** [comment]
i'm going to have to re-commit this. a bunch of these files i didn't even touch

**Comment by andrewm4894** [comment]
@rsandb i'd suggest leaving rsandb:main to just be a copy of [LAION-AI:main](https://github.com/LAION-AI/Open-Assistant) and doing your work in a specific feature branch in your fork then you can make a pr of 

rsandb:some-feature-branch -> LAION-AI:main

and it means you can just keep updating rsandb:main from LAION-AI:main to keep them in sync and then whgen you ready to do a PR you can update rsandb:some-feature-branch from either upstream/main (LAION-AI:main) or from an updated rsandb:main and then rsandb:some-feature-branch should end up nice and clean in the PR to LAION-AI:main

Thats at least how i have been doing things as so much going on it can be very easy to mess up your forks main and that can them get crazy, at least with feature branches and a clean main in you own fork you can always just kill your branch and start on a fresh one worst case,

**Comment by rsandb** [comment]
That sounds a lot better than what I've been doing haha, I'll start doing that. I really appreciate the tip, thank you!

**Pull request closed without merging**
