### PR TITLE
PII Detector added

### PR DESCRIPTION
**Pull request by Simon1V**
Regex based PII Detector module  to identify access tokens, emails, social security numbers and such in strings of text. 

(Issue: https://github.com/LAION-AI/Open-Assistant/issues/2355)

### CODE REVIEW

**Comment by andreaskoepf** [comment]
looks good .. please run pre-commit ... :-)

**Comment by Simon1V** [comment]
"detect private key.......................................................Failed"

Yes, the detector running on pii_detector.py detects the very same sequences, ironic

**Comment by yk** [comment]
could we re-name this to something more accurate, like regex pii detector or so?

also, maybe there's a way to exclude certain files / lines from pre-commit. if you can't find anything, let us know, we may have to force-override it

**Comment by olliestanley** [comment]
The way to exclude files from pre-commit is here: https://github.com/LAION-AI/Open-Assistant/blob/main/.pre-commit-config.yaml#L29

**Comment by Simon1V** [comment]
That worked out!
I renamed the file to regex_pii_detector.py, runt he shebang fix suggested by pre-commit's error logging system and added an exception to .pre-commit-config.yaml to regex_pii_detector.py

**Review by yk — APPROVED** [review]
thank you

**Pull request merged**
