### PR TITLE
add lang filter option to message endpoints

### PR DESCRIPTION
**Pull request by j0rd1smit**
# add lang filter option to message endpoints
Fixes issues #896

As descriped in the issues, I added a lang filter option to:
- `api/v1/messages`
- `api/v1/messages/cursor`
- `api/v1/users/{user-id}/messages`
- `api/v1/users/{user-id}/messages/cursor`

I saw that `query_messages_ordered_by_created_date()` is also used in `/api/v1/frontend_users/{auth_method}/{username}/messages` and ``/api/v1/frontend_users/{auth_method}/{username}/messages/cursor`. However, I did not add the lang filter to this endpoint since the issues did not specify this endpoint. So, I was unsure if this was desired or not. Let me know if you also want it there, it is an easy fix.

### CODE REVIEW

**Review by andreaskoepf — APPROVED** [review]
nice job. :-)

**Comment by andreaskoepf** [comment]
> However, I did not add the lang filter to this endpoint since the issues did not specify this endpoint. So, I was unsure if this was desired or not. Let me know if you also want it there, it is an easy fix.

Yes, I think it would be useful to have the same lang query-param for the other places that you identified, too. If you have time to do it, please add it. Otherwise I will merge this PR in 24h.

**Comment by j0rd1smit** [comment]
> If you have time to do it, please add it

Done 😀

**Review by andreaskoepf — APPROVED** [review]
lgtm!

**Pull request merged**
