### PR TITLE
Evaluation datasets for Reward Model

### PR DESCRIPTION
**Pull request by shahules786**
I have added support for the following datasets for Reward Modeling.

HellaSwag: https://huggingface.co/datasets/hellaswag
Stanford/SHP: https://huggingface.co/datasets/stanfordnlp/SHP 
summarize_from_feedback :https://huggingface.co/datasets/openai/summarize_from_feedback

I chose to add the files into `model_training` due to changes according to #2071 

fixes : #2090

### CODE REVIEW

**Comment by sanagno** [comment]
Hey thanks a lot that looks great. In the current format the first part of the returned tuple should be a list of messages indicating the previous conversation. Can you modify the datasets, so the first element is a list here as well?

**Comment by shahules786** [comment]
@sanagno Done.

**Review by sanagno — APPROVED** [review]
Looks good

**Comment by sanagno** [comment]
We should also add the datasets in the https://github.com/LAION-AI/Open-Assistant/blob/main/model/model_training/custom_datasets/__init__.py#L29 and in the get_one_dataset function https://github.com/LAION-AI/Open-Assistant/blob/main/model/model_training/custom_datasets/__init__.py#L42.

**Pull request merged**
