### PR TITLE
added my essay notebook and data_argumentation.md to docs

### PR DESCRIPTION
**Pull request by GravermanDev**
I added my essay for data argumentation of essays, it turns any essay into a set of instructions. I also did some much needed work on docs. Added a file about data argumentation so anyone can check what that means and how they can contribute. I also moved prompting guide to `docs/` as I think it should be there, makes it a little easier to find for someone looking to get more info.

Added another notebook for essay revision, it generates data helpful for revising essays. I also added markdown files related to the changes explaining the files in more detail

### CODE REVIEW

**Comment by fozziethebeat** [comment]
Could you add a bit more description to the pull request?

**Comment by GravermanDev** [comment]
oh yeah, sorry, I was asked to do this PR by Yannic so I just did and didn't think much on describing

**Review by yk — APPROVED** [review]

**Comment by yk** [comment]
awesome, thank you very much!

**Comment by yk** [comment]
could you run `pre-commit run --all-files` to make the linter happy?

**Comment by GravermanDev** [comment]
okay, I never used pre-commit so I have no idea if I did it correctly but it seams like it did add new line to the files

**Comment by yk** [comment]
yes, it does some fixes and for other things it just yells at you. you can `pre-commit install` so it does it automatically in the future and prevents committing if things aren't ok.

Now there appear to be some conflicts preventing auto-merge. Could you merge origin's `main` into your branch and then push agaiin?

**Comment by yk** [comment]
@GravermanDev did you close this PR on purpose?

**Comment by yk** [comment]
ah just saw the other comment, my bad :) ignore above

**Pull request closed without merging**
