### PR TITLE
Safety pipeline prototype

### PR DESCRIPTION
**Pull request by shahules786**
The safety team has decided to maintain a `safety` folder. This folder will contain

1. Documentation related to safety models.
2. Reproducible training and evaluation code for safety models.
3. Inference pipelines for safety models

@ontocord

### CODE REVIEW

**Comment by ontocord** [comment]
It looks good to me!

**Comment by SummerSigh** [comment]
Awesome! Looks good! I'll add a readme talking about the goals of the safety team and some basic folder layout documentation.

**Comment by shahules786** [comment]
@SummerSigh, can you push your documentation to the same branch?

**Review by andreaskoepf — APPROVED** [review]
Really nice and clean, thanks a lot!

**Pull request merged**
