### PR TITLE
Create readme.md

### PR DESCRIPTION
**Pull request by thaumstrial**
t5-flan-encoder experiment result

### CODE REVIEW

**Comment by sanagno** [comment]
Hey @thaumstrial, are you doing anything substantially different that what is already done in the current reward model?

**Comment by thaumstrial** [comment]
@sanagno No, just experiment t5-flan-encoder combined with the idea of rankgen as the reward model

**Comment by andrewm4894** [comment]
I wonder if stuff like this might make sense as blog posts under /docs with appropriate tags. Would be easy enough to extend our docs site to include a blog section as this is really easy to just enable via docusaruas.

**Comment by thaumstrial** [comment]
@andrewm4894 OK, I'll put it under /docs

**Comment by andrewm4894** [comment]
Maybe let's see what @yk @andreaskoepf and others think.

**Comment by andrewm4894** [comment]
If not a blog then for sure an experiments section on docs site also by easy to add.

**Comment by andrewm4894** [comment]
Made issue here to discuss the blog question

https://github.com/LAION-AI/Open-Assistant/issues/1093

**Pull request closed without merging**
