### PR TITLE
Bth5032/78 blackcat trainer

### PR DESCRIPTION
**Pull request by bth5032**
#78 

As per discussion with @theblackcat102 I built the rankgen trainer on top of their framework ([wandb](https://wandb.ai/bobakhashemi/reward-model/runs/2sgitozt?workspace=user-bobakhashemi)). The model seems to be training now in fp32. Apparently t5 has some issue with fp16. Blackcat suggested scaling the weights might help as in [1](https://github.com/LAION-AI/Open-Assistant/blob/main/model/reward/instructor/trainer.py). This could be a good next step if we want to move with this model. Until then, I think this code is worth comitting since it shows how to add new models which are not `AutoModelForSequenceClassification`

### CODE REVIEW

**Comment by theblackcat102** [comment]
@bth5032 your wandb loss looks good, but I wonder why is the accuracy validation missing?

Not trying to nickpick anyway, but just curious why not assign the default value for tokenizer_name is same as model_name at the [argument_parser](https://github.com/bth5032/Open-Assistant/blob/bth5032/78-blackcat-trainer/model/reward/instructor/utils.py#L94)  then we can remove this if else at the trainer [here](https://github.com/bth5032/Open-Assistant/blob/bth5032/78-blackcat-trainer/model/reward/instructor/trainer.py#L200)

But overall the code looks good

**Review by theblackcat102 — APPROVED** [review]
looks good

**Review by sanagno — APPROVED** [review]
Thanks a lot!

**Comment by yk** [comment]
@bth5032 thank you! could you run `pre-commit run --all-files` to make linters happy?

**Comment by bth5032** [comment]
> @bth5032 thank you! could you run `pre-commit run --all-files` to make linters happy?

Thanks! 

> Not trying to nickpick anyway, but just curious why not assign the default value for tokenizer_name is same as model_name at the [argument_parser](https://github.com/bth5032/Open-Assistant/blob/bth5032/78-blackcat-trainer/model/reward/instructor/utils.py#L94) then we can remove this if else at the trainer [here](https://github.com/bth5032/Open-Assistant/blob/bth5032/78-blackcat-trainer/model/reward/instructor/trainer.py#L200)

Ah, I normally use hydra/omegaconf for this, didn't realize you had that utility function, will update and push another. I cleaned that up

> @bth5032 your wandb loss looks good, but I wonder why is the accuracy validation missing?

I've been trying to figure that out myself. The `compute_metrics` function never runs for me... I found [this thread](https://discuss.huggingface.co/t/trainer-never-invokes-compute-metrics/11440/6) and tried setting up `evaluation_strategy=IntervalStrategy.STEPS` and a few other things. But ultimately I verified the condition they listed [here](https://github.com/huggingface/transformers/blob/8afaaa26f5754948f4ddf8f31d70d0293488a897/src/transformers/trainer_callback.py#L419-L423) is true. However I still don't ever see `compute_metrics` evaluating...

I'll keep looking into it and submit a PR if I figure it out.


@theblackcat102 @sanagno should be ready for merge.

**Review by theblackcat102 — COMMENTED** [review]
looks good

**Review by theblackcat102 — COMMENTED** [review]
models.py is fine

**Pull request merged**
